[2022-06-03 21:05:58,084] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: UK_COVID19_dag.Plot_UK_Data 2022-06-02T20:58:06.025617+00:00 [queued]>
[2022-06-03 21:05:58,111] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: UK_COVID19_dag.Plot_UK_Data 2022-06-02T20:58:06.025617+00:00 [queued]>
[2022-06-03 21:05:58,112] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 21:05:58,113] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-06-03 21:05:58,115] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 21:05:58,134] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): Plot_UK_Data> on 2022-06-02T20:58:06.025617+00:00
[2022-06-03 21:05:58,140] {standard_task_runner.py:52} INFO - Started process 63 to run task
[2022-06-03 21:05:58,154] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'UK_COVID19_dag', 'Plot_UK_Data', '2022-06-02T20:58:06.025617+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/covid_dag-checkpoint.py', '--cfg-path', '/tmp/tmpkpj5os_d', '--error-file', '/tmp/tmpyeos91zj']
[2022-06-03 21:05:58,155] {standard_task_runner.py:77} INFO - Job 7: Subtask Plot_UK_Data
[2022-06-03 21:05:58,241] {logging_mixin.py:104} INFO - Running <TaskInstance: UK_COVID19_dag.Plot_UK_Data 2022-06-02T20:58:06.025617+00:00 [running]> on host 125d245880e1
[2022-06-03 21:05:58,377] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Huda
AIRFLOW_CTX_DAG_ID=UK_COVID19_dag
AIRFLOW_CTX_TASK_ID=Plot_UK_Data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T20:58:06.025617+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-02T20:58:06.025617+00:00
[2022-06-03 21:06:00,967] {__init__.py:482} WARNING - Matplotlib created a temporary config/cache directory at /tmp/matplotlib-wlyg0csm because the default path (/home/airflow/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
[2022-06-03 21:06:01,599] {font_manager.py:1423} INFO - Generating new fontManager, this may take some time...
[2022-06-03 21:06:02,745] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: '/opt/airflow/data/DF_UK_Scaled.csv'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/covid_dag-checkpoint.py", line 73, in Plotting
    DF_UK_u_3 = pd.read_csv('/opt/airflow/data/DF_UK_Scaled.csv', parse_dates=['Day'])
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/DF_UK_Scaled.csv'
[2022-06-03 21:06:02,770] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=UK_COVID19_dag, task_id=Plot_UK_Data, execution_date=20220602T205806, start_date=20220603T210558, end_date=20220603T210602
[2022-06-03 21:06:03,011] {local_task_job.py:146} INFO - Task exited with return code 1
