[2022-06-03 21:08:17,906] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: UK_COVID19_dag.Push_Data_to_Postgres 2022-06-02T20:58:06.025617+00:00 [queued]>
[2022-06-03 21:08:17,930] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: UK_COVID19_dag.Push_Data_to_Postgres 2022-06-02T20:58:06.025617+00:00 [queued]>
[2022-06-03 21:08:17,931] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 21:08:17,933] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-06-03 21:08:17,935] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 21:08:17,960] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): Push_Data_to_Postgres> on 2022-06-02T20:58:06.025617+00:00
[2022-06-03 21:08:17,969] {standard_task_runner.py:52} INFO - Started process 75 to run task
[2022-06-03 21:08:17,976] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'UK_COVID19_dag', 'Push_Data_to_Postgres', '2022-06-02T20:58:06.025617+00:00', '--job-id', '10', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/covid_dag-checkpoint.py', '--cfg-path', '/tmp/tmpkwl74ivc', '--error-file', '/tmp/tmpb8zk26r6']
[2022-06-03 21:08:17,981] {standard_task_runner.py:77} INFO - Job 10: Subtask Push_Data_to_Postgres
[2022-06-03 21:08:18,110] {logging_mixin.py:104} INFO - Running <TaskInstance: UK_COVID19_dag.Push_Data_to_Postgres 2022-06-02T20:58:06.025617+00:00 [running]> on host 125d245880e1
[2022-06-03 21:08:18,446] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Huda
AIRFLOW_CTX_DAG_ID=UK_COVID19_dag
AIRFLOW_CTX_TASK_ID=Push_Data_to_Postgres
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T20:58:06.025617+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-02T20:58:06.025617+00:00
[2022-06-03 21:08:21,268] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: '/opt/airflow/data/DF_UK_Scaled.csv'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/covid_dag-checkpoint.py", line 85, in CSV_to_Postgres
    DF_UK_Scaled = pd.read_csv('/opt/airflow/data/DF_UK_Scaled.csv', parse_dates=['Day'])
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/DF_UK_Scaled.csv'
[2022-06-03 21:08:21,285] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=UK_COVID19_dag, task_id=Push_Data_to_Postgres, execution_date=20220602T205806, start_date=20220603T210817, end_date=20220603T210821
[2022-06-03 21:08:21,397] {local_task_job.py:146} INFO - Task exited with return code 1
